import { ErrorCode } from '@motus/types';

export const HTTP_CODE_MAP: Record<ErrorCode, number> = {
  [ErrorCode.MOTUS_DRIVER_NOT_FOUND]: 404,
  [ErrorCode.MOTUS_SESSION_NOT_FOUND]: 404,
  [ErrorCode.MOTUS_INVALID_TRANSITION]: 422,
  [ErrorCode.MOTUS_DRIVER_BUSY]: 409,
  [ErrorCode.MOTUS_CAPACITY_EXCEEDED]: 429,
  [ErrorCode.MOTUS_INVALID_VEHICLE_TYPE]: 400,
  [ErrorCode.MOTUS_LOCK_ACQUISITION_FAILED]: 409,
  [ErrorCode.MOTUS_INVALID_ARGUMENT]: 400,
  [ErrorCode.MOTUS_UNAUTHORIZED]: 401,
  [ErrorCode.MOTUS_INTERNAL_ERROR]: 500
};

export const WEBSOCKET_CODE_MAP: Record<ErrorCode, number> = {
  [ErrorCode.MOTUS_DRIVER_NOT_FOUND]: 4404,
  [ErrorCode.MOTUS_SESSION_NOT_FOUND]: 4405,
  [ErrorCode.MOTUS_INVALID_TRANSITION]: 4422,
  [ErrorCode.MOTUS_DRIVER_BUSY]: 4409,
  [ErrorCode.MOTUS_CAPACITY_EXCEEDED]: 4429,
  [ErrorCode.MOTUS_INVALID_VEHICLE_TYPE]: 4400,
  [ErrorCode.MOTUS_LOCK_ACQUISITION_FAILED]: 4423,
  [ErrorCode.MOTUS_INVALID_ARGUMENT]: 4401,
  [ErrorCode.MOTUS_UNAUTHORIZED]: 4403,
  [ErrorCode.MOTUS_INTERNAL_ERROR]: 5000
};
